# Generated by Django 5.0.6 on 2024-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='is_challenging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizes',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
